### ISSUE TITLE
[META] Checklist for feature freeze December 2023

### ISSUE THREAD

**Issue by wofsauge** [TeamREPENTOGON/REPENTOGON#135]
A small list to keep track of things we can do while we are in feature freeze mode from 01. december onwards:

## General things to do:
- [x] Bugfixing
- [x] Testing features
- [x] Implement ridable dragons
- [x] Polishing existing features

## Important Features 
- [x] grid entity callbacks

## Documentation, Deployment & Releases
- [x] Develop an (automatic) update process
- [ ] Update list of resolved issues https://github.com/IsaacZHL/REPENTOGON/issues/81
- [x] Check existing issues, if they can be closed
- [ ] Update documentation website
  - [x] ModCallbacks page
  - [x] Add undocumented functions/attributes
  - [ ] Make sure "deleted" functions are no longer listed in the documentation
  - [x] "How to access class" Infoboxes for all pages if possible
  - [x] Sort pages into better groups
  - [ ] Update "Changes" pages
