### ISSUE TITLE
Launcher TODO List

### ISSUE THREAD

**Issue by Sylmir** [TeamREPENTOGON/REPENTOGON#546]
- [ ] Update the download checks in the launcher to include zhlLoader.dll
- [ ] Update zhlLoader to have a version variable. While the loader should be frozen, better safe than sorry
- [ ] Update release scripts to include zhlLoader.dll as part of the shipped files
- [ ] Update libzhl to include a check of the presence of dsound.dll and whether or not it is our dsound.dll. People upgrading to 1.1.0 from a legacy installation will do so through the old updater, which will result in an unstable installation. This check in libzhl will prompt the user to launch the game through the launcher, which will in turn stabilize the installation.
- [ ] Add CLI support in the launcher
- [ ] Add BR support in the launcher
- [ ] Create a transitional release to prepare for the alpha of the launcher. This release will be a pre-release: the first true release to include the launcher will be 1.1.0. This pre-release will include the loader and people who want to test the launcher will get an alpha release of the launcher.
- [ ] Fix bugs pointed out by people testing the launcher
- [ ] Stabilize main Repentogon branch, rebase main on top of sylmir/testing-launcher then reset main to sylmir/testing-launcher. Release as 1.1.0

Miscellaneous things:

- New releases of Repentogon will need to be followed by a new version of the transitional release afterwards, in order to maintain the pre-release as the latest release.
- Transitional releases may contain (more) unstable (than usual) Repentogon content, and may be out-of-sync with Repentogon releases.
