### ISSUE TITLE
[META] Online coop checklist

### ISSUE THREAD

**Issue by Sylmir** [TeamREPENTOGON/REPENTOGON#591]
- [ ] Correct broken signatures
- [ ] Realign structures (= check that fields have not moved around)
- [ ] Individually test functions to ensure they match with the appropriate function in the executable

**Comment by jerbmega** [comment]
There's no clearcut way of defining a "client based" mod because Isaac was never meant with this structure in mind. It's an all or nothing deal and even just changing animations can cause a desync as some entities have event triggers within animations.

It is far too early to be discussing online mods. We need to get the thing ported first and wait for the dust to settle, features come later.

**Comment by GamingInfinite** [comment]
fair enough.  I just miss EID bc my brain is bad at remembering things

**Comment by BadPig03** [comment]
According to the changelog, "Mod creators will need to update their mods for compatibility. If you copy Repentance or AB+ mods into this folder, YOU DO SO AT YOUR OWN RISK as things are likely to break." Do you think this indicates actual changes to the API, or is it just a standard disclaimer?

**Comment by jsgnextortex** [comment]
We dont think, WE KNOW and CONFIRMED that the api is just fucked on several places....they probably just used that as an excuse to buy time and have people blame modders for a while.

**Comment by jerbmega** [comment]
MenuManager::RenderButtonLayout was inlined, thus we likely need to move MC_MAIN_MENU_RENDER to an ASM patch.

**Comment by jsgnextortex** [comment]
Added a new section at the bottom where we can shove pending mismatches that we are not able to solve immediately so maybe others can in the meantime. First one in there to break the ice is Entity_Player::ReviveFromCollectible (currently matching Grid_Fire::Update)

**Comment by Denyscrasav4ik** [comment]
A new update released, so how much did it break/fix the modding stuff?

**Comment by epfly6** [comment]
> A new update released, so how much did it break/fix the modding stuff?

Like this
![image-47](https://github.com/user-attachments/assets/fad29ae9-1771-4daf-802b-57ee667763c9)

**Comment by jerbmega** [comment]
> A new update released, so how much did it break/fix the modding stuff?

Nicalis made a lot of positive changes to the API in the latest update but also mistakenly removed a feature mods were using to tell if they were running on AB+ or Repentance. Without actually checking, I'd guess mods might be *more* broken now compared to last patch as a result. We've already notified them.

**Comment by nyabinary** [comment]
Why did so much stuff get inlined?

**Comment by namishere** [comment]
as a prank (optimized out heuristically by compiler)

**Comment by jsgnextortex** [comment]
The compiler gods did not smile upon us

**Comment by haohanyuzmx** [comment]
我没太读懂这里的讨论，这里指的是它不支持在线联机吗，如果我安装了这个模组，当我想要联机的时候我需要在游戏启动项设置禁用改模组吗

![Image](https://github.com/user-attachments/assets/14ae6669-a531-48b3-913a-ad6a1b2681b1)

**Comment by haohanyuzmx** [comment]
I don't quite understand the discussion here. Does it mean that this mod does not support online connection? If I install this mod, do I need to disable it in the startup options when I want to online co-op? I also search web page, but I don't get answer

**Comment by epfly6** [comment]
> I don't quite understand the discussion here. Does it mean that this mod does not support online connection? If I install this mod, do I need to disable it in the startup options when I want to online co-op? I also search web page, but I don't get answer

Repentance+ version of Repentogon will disable access to the online mode (except for Daily Runs)

**Comment by epfly6** [comment]
> > I don't quite understand the discussion here. Does it mean that this mod does not support online connection? If I install this mod, do I need to disable it in the startup options when I want to online co-op? I also search web page, but I don't get answer
> 
> Repentance+ version of Repentogon will disable access to the online mode (except for Daily Runs)

![Image](https://github.com/user-attachments/assets/42b55037-91c1-4a1f-bb6a-339bb16e0d23)

**Comment by jsgnextortex** [comment]
Nothing new here, you cannot play co-op with mods, repentogon is a mod.
