### ISSUE TITLE
[Roadmap] ImGui Lua binding

### ISSUE THREAD

**Issue by wofsauge** [TeamREPENTOGON/REPENTOGON#90]
This issue is used as a collection of planned imGui Lua bindings.

Feel free to add and suggest stuff.

- [x] Basic Elements
     - [x] Text
     - [x] TextWrapped
     - [x] Trees
     - [x] Collapsable Headers
     - [x] Bulletpoints
     - [x] Seperators
     - [x] Buttons
- [x] Windows
- [x] Menus
- [x] Callbacks
- [x] Popups
- [x] AddTooltip
- [x] AddInput
     - [x] Text
     - [x] Int
     - [x] Float
     - [x] Combobox (choose an entry of a table via a dropdown menu)
     - [x] Color
     - [x] Enum Slider
- [x] AddSliderInput
     - [x] Int
     - [x] Float
- [x] Checkbox
- [x] RadioButtons
- [x] Plots
- [x] Tabs
- [x] Progressbar
- [x] WorldToImGuiPosition() and ImGuiToWorldPosition() 
- [x] Allow ImGui Window to be visible in gameplay
- [x] Controller / Keyboard Input
- [x] Function to update element data
